create table if not exists
  images (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    title text not null,
    src text not null,
    tags text[] not null,
    href text null
  );

alter table images enable row level security;

create policy "Anyone can see the images" on images
for select
to public
using (true)
